version: '3'

services:

  mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root  
      volumes: 
      - /home/ricardo/Cursos/Pedbot/Docker:/var/lib/mysql

  php:
      image: phpmyadmin
      restart: always
      ports:
        - 9001:80
      environment:
        - PMA_ARBITRARY=1
      volumes:
      - /home/ricardo/Cursos/Pedbot/Docker:/var/lib/phpmyadmin