version: '3'

services:

  mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
      - 3307:3306
      environment:
        MYSQL_ROOT_PASSWORD: root  
      volumes: 
      - ./:/var/lib/mysql
      networks:
      - rede_docker
      
              

  php:
      image: phpmyadmin
      restart: always
      ports:
        - 9001:80
      environment:
        - PMA_HOST= docker_mysql_1
      volumes:
        - ./:/var/lib/phpmyadmin
      networks:
      - rede_docker
      

networks:
  rede_docker:
    driver: bridge
    


           

